version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres-booking
    environment:
      POSTGRES_USER: bookingJC
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bookingJC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking-network

  app:
    image: openjdk:17-jdk-slim
    container_name: spring-boot-booking
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookingJC
      SPRING_DATASOURCE_USERNAME: bookingJC
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_APPLICATION_NAME: booking
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app
    working_dir: /app
    entrypoint: ["java", "-jar", "your-app.jar"]
    depends_on:
      - postgres
    networks:
      - booking-network

  keycloak-mysql:
    container_name: keycloak-mysql-container
    image: mysql:latest
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    networks:
      - booking-network

  keycloak:
    container_name: keycloak-container
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql
    networks:
      - booking-network

volumes:
  postgres_data:

networks:
  booking-network:
    driver: bridge
